### ISSUE TITLE
Unable to load data from S3

### ISSUE THREAD

**Issue by edwardxtgvivid** [USEPA/stateio#29]
Hi StateIOR team,

I've successfully installed stateior but when trying to access the final data products (as per usage type 1) I get the below error:

![image](https://github.com/USEPA/stateior/assets/112706526/cdb6d477-2669-4b0a-b6de-73581ffde0fa)

Following the link to S3 in the above error takes me to this error:

![image](https://github.com/USEPA/stateior/assets/112706526/dcf7d987-747e-4568-821b-6acf4c7fc0fe)

The S3 bucket is possibly down?

Grateful if someone could take a look.

Many thanks
Edward

**Comment by bl-young** [comment]
Make sure to (re-)install from the latest commit on Master.
